In [1]:
import do_functions as do
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import f1_score
from sklearn.metrics import auc
from sklearn.metrics import matthews_corrcoef
from sklearn.metrics import confusion_matrix



In [2]:
df = do.read_and_merge('paz_metadata_actualitzat.pkl',
                       'paz_profiles_actualitzat.pkl')
df = do.clean_dataframe(df)

In [3]:
df

roid    lat     lon         startimeUTC  az_surf  \
0      PAZ1.2018.130.20.55.G18  37.48  126.10 2018-05-10 20:55:41   -30.59   
1      PAZ1.2018.130.21.01.G19   4.68  153.15 2018-05-10 21:01:40    61.29   
2      PAZ1.2018.130.21.10.G24 -16.88  135.77 2018-05-10 21:10:33    19.90   
3      PAZ1.2018.130.21.16.G10 -36.43  112.66 2018-05-10 21:16:14    -7.23   
4      PAZ1.2018.130.21.39.G29 -53.91  -64.58 2018-05-10 21:39:06  -147.99   
...                        ...    ...     ...                 ...      ...   
93052  PAZ1.2022.031.20.14.G13 -27.16  138.07 2022-01-31 20:13:55     1.13   
93053  PAZ1.2022.031.20.56.G31  13.31  -36.69 2022-01-31 20:56:57   151.54   
93054  PAZ1.2022.031.21.00.G03  24.62  -53.73 2022-01-31 21:00:29  -179.48   
93055  PAZ1.2022.031.21.04.G04  38.95  -67.93 2022-01-31 21:04:21  -169.71   
93056  PAZ1.2022.031.22.21.G02 -23.27  -78.20 2022-01-31 22:21:36  -144.27   

       meanP_2  precipBelow12  precipBelow6  irTemp_below  dphi_0010  ...  \
0         0.00          0.001         0.000           236  -0.055016  ...   
1         0.03          0.044         0.040           211  -0.017083  ...   
2         0.00          0.001         0.000           242  -0.065611  ...   
3         0.00          0.000         0.000           251   0.020166  ...   
4         0.01          0.004         0.002           228   0.030036  ...   
...        ...            ...           ...           ...        ...  ...   
93052     0.54          0.697         0.671           224   1.841160  ...   
93053     0.00          0.000         0.000           270  -0.085092  ...   
93054     0.04          0.012         0.014           232  -0.325563  ...   
93055     0.07          0.017         0.045           252  -0.873391  ...   
93056     0.00          0.000         0.000           277  -0.123094  ...   

           h391      h392      h393      h394      h395      h396      h397  \
0      0.657319  0.561302  0.453678  0.413606  0.423642  0.358429  0.313858   
1      0.388286  0.376438  0.316907  0.303784  0.237429  0.229576  0.131511   
2     -0.096078 -0.092646 -0.021363 -0.009680 -0.004799 -0.060674 -0.032557   
3     -0.017869 -0.089222 -0.166217 -0.170754 -0.122106 -0.222287 -0.267388   
4      0.015577  0.010131 -0.007171 -0.013827  0.019190  0.006500  0.052092   
...         ...       ...       ...       ...       ...       ...       ...   
93052 -0.187433 -0.265384 -0.251428 -0.209926 -0.228418 -0.188364 -0.144678   
93053 -0.077407 -0.070182 -0.059642 -0.022276  0.018134 -0.010405  0.012951   
93054  0.124019  0.113161  0.103820  0.077413  0.100516  0.145444  0.136346   
93055  0.039079  0.040218 -0.025640  0.015339  0.024858  0.055605  0.035608   
93056 -0.106615 -0.154835 -0.127584 -0.110332 -0.113023 -0.110772 -0.028137   

           h398      h399      h400  
0      0.299540  0.329093  0.301198  
1      0.020837 -0.010168 -0.107573  
2      0.026656  0.083702  0.040231  
3     -0.316209 -0.349521 -0.330845  
4      0.063766  0.077721  0.111858  
...         ...       ...       ...  
93052 -0.114919 -0.165454 -0.148727  
93053  0.041839 -0.032065 -0.049576  
93054  0.124060  0.137998  0.094240  
93055  0.089771  0.103440  0.132603  
93056  0.056196  0.070251  0.109150  

[90862 rows x 412 columns]

### MCC for 99 percentile optimal range

In [4]:
df_avg = do.average(df,0.1,6.4)
len(df_avg)

39598

In [5]:
y_true = df_avg['precipBelow6'].to_numpy()>4.7
y_pred = df_avg['avgh001h064'].to_numpy()>10

In [6]:
matthews_corrcoef(y_true, y_pred)

0.4171526803854732

In [7]:
confusion_matrix(y_true, y_pred)

array([[39353,    87],
       [   93,    65]])

### MCC for 98 percentile optimal range

In [8]:
df_avg = do.average(df,0.1,7.7)
len(df_avg)

48158

In [9]:
y_true = df_avg['precipBelow6'].to_numpy()>3.32
y_pred = df_avg['avgh001h077'].to_numpy()>6.75
matthews_corrcoef(y_true, y_pred)

0.4595199099821819

In [10]:
confusion_matrix(y_true, y_pred)

array([[47553,   242],
       [  181,   182]])

### MCC for 97 percentile optimal range

In [11]:
df_avg = do.average(df,0.1,6.0)
len(df_avg)

39598

In [12]:
y_true = df_avg['precipBelow6'].to_numpy()>2.76
y_pred = df_avg['avgh001h060'].to_numpy()>5.94
matthews_corrcoef(y_true, y_pred)

0.5152869846870696

In [13]:
confusion_matrix(y_true, y_pred)

array([[38792,   336],
       [  189,   281]])

### MCC for 96 percentile optimal range

In [14]:
df_avg = do.average(df,0.1,6.0)
len(df_avg)

39598

In [15]:
y_true = df_avg['precipBelow6'].to_numpy()>1.0
y_pred = df_avg['avgh001h060'].to_numpy()>1.5
matthews_corrcoef(y_true, y_pred)

0.49732317283188093

In [16]:
confusion_matrix(y_true, y_pred)

array([[34900,  2955],
       [  276,  1467]])

### MCC for 95 percentile optimal range

In [18]:
df_avg = do.average(df,0.1,7.3)
len(df_avg)

45044

In [19]:
y_true = df_avg['precipBelow6'].to_numpy()>1.95
y_pred = df_avg['avgh001h073'].to_numpy()>4.53
matthews_corrcoef(y_true, y_pred)

0.5262394447436713

In [20]:
confusion_matrix(y_true, y_pred)

array([[43699,   483],
       [  371,   491]])

### MCC for 94 percentile optimal range

In [21]:
df_avg = do.average(df,0.1,6.8)
len(df_avg)

42599

In [22]:
y_true = df_avg['precipBelow6'].to_numpy()>1.73
y_pred = df_avg['avgh001h068'].to_numpy()>4.29
matthews_corrcoef(y_true, y_pred)

0.5394808295129833

In [23]:
confusion_matrix(y_true, y_pred)

array([[41070,   532],
       [  417,   580]])

### MCC for 93 percentile optimal range

In [24]:
df_avg = do.average(df,0.1,7.4)
len(df_avg)

45044

In [25]:
y_true = df_avg['precipBelow6'].to_numpy()>1.50
y_pred = df_avg['avgh001h074'].to_numpy()>3.79
matthews_corrcoef(y_true, y_pred)

0.5467261991339092

In [26]:
confusion_matrix(y_true, y_pred)

array([[43216,   615],
       [  504,   709]])

### MCC for 92 percentile optimal range

In [27]:
df_avg = do.average(df,0.2,6.7)
len(df_avg)

45044

In [28]:
y_true = df_avg['precipBelow6'].to_numpy()>1.31
y_pred = df_avg['avgh002h067'].to_numpy()>3.33
matthews_corrcoef(y_true, y_pred)

0.5618726327612388

In [29]:
confusion_matrix(y_true, y_pred)

array([[42818,   821],
       [  509,   896]])

### MCC for 91 percentile optimal range

In [30]:
df_avg = do.average(df,0.1,5.2)
len(df_avg)

34338

In [32]:
y_true = df_avg['precipBelow6'].to_numpy()>1.24
y_pred = df_avg['avgh001h052'].to_numpy()>3.52
matthews_corrcoef(y_true, y_pred)

0.5734978833744017

In [33]:
confusion_matrix(y_true, y_pred)

array([[32387,   713],
       [  427,   811]])

### MCC for 90 percentile optimal range

In [34]:
df_avg = do.average(df,0.7,8.6)
len(df_avg)

68174

In [36]:
y_true = df_avg['precipBelow6'].to_numpy()>1.04
y_pred = df_avg['avgh007h086'].to_numpy()>2.46
matthews_corrcoef(y_true, y_pred)

0.5755146597417428

In [37]:
confusion_matrix(y_true, y_pred)

array([[64616,  1251],
       [  822,  1485]])